variables:
  GIT_DEPTH: 0

build:
  stage: build
  image: ubuntu:25.04
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential cmake ninja-build pkg-config git qt6-base-dev qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools qt6-charts-dev qt6-qmltooling-plugins libdbus-1-dev libsystemd-dev linux-headers-$(uname -r)
  script:
    - git submodule update --init --recursive
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - cmake --build .
  only:
    - main

sync_to_github:
  stage: deploy
  image: docker:20.10
  script:
    - apk add --no-cache git
    - git checkout main
    - git branch --set-upstream-to=origin/main main
    - git pull --rebase origin main
    - git push https://$GITHUB_TOKEN@github.com/AcNasDev/MsiController.git
  only:
    - main