name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: docker
    container:
      image: node:20-bullseye
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            build-essential cmake ninja-build pkg-config git \
            qt6-base-dev qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools \
            qt6-charts-dev qt6-qmltooling-plugins libdbus-1-dev libsystemd-dev \
            linux-headers-$(uname -r)
      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake .. -G Ninja
          cmake --build .

  clazy_check:
    runs-on: docker
    container:
      image: node:20-bullseye
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            build-essential cmake ninja-build pkg-config git \
            qt6-base-dev qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools \
            qt6-charts-dev qt6-qmltooling-plugins libdbus-1-dev libsystemd-dev \
            linux-headers-$(uname -r) clang-tools clang-tidy clazy
      - name: Clazy check
        run: |
          mkdir -p build
          export CLAZY_CHECKS=level1
          export CXX_FLAGS="-Werror -Wall -Wextra"
          cd build
          cmake .. -G Ninja -DCMAKE_CXX_COMPILER=clazy -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra"
          cmake --build . --parallel

  sync_to_github:
    runs-on: docker
    container:
      image: node:20-bullseye
    steps:
      - uses: actions/checkout@v4
      - name: Install git and curl
        run: |
          apt-get update
          apt-get install -y git curl
      - name: Sync to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout main
          git branch --set-upstream-to=origin/main main
          git pull --rebase origin main
          git push https://$GITHUB_TOKEN@github.com/AcNasDev/MsiController.git
